# Numpy Array

In [1]:
print("Welcome to Machine Learning")

Welcome to Machine Learning


In [2]:
import numpy as np


## Array Creation

**Array Dimension**

In [3]:
import numpy as np

In [4]:
# 0-d array
a = np.array([1])
a


array([1])

In [5]:
# 1-d array (Scalar or zero Rank tensor)
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [85]:
# 2-d array  (vector or 1st Rank tensor)
b = np.array([[1,2,3],[5,6,7]])
b

array([[1, 2, 3],
       [5, 6, 7]])

In [163]:
#3-d array  (tesnsor)
c = np.array([[[1,2,3],[4,5,6]],[[4,3,2],[7,64,4]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 4,  3,  2],
        [ 7, 64,  4]]])

**np.ones and np.zeros**

In [164]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [165]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [240]:
np.zeros((2,6)).reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [241]:
np.zeros((4,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [168]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [169]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [170]:
np.ones((2,4)).reshape(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [171]:
np.ones((2,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [172]:
x = np.ones((2,3))
x.dtype


dtype('float64')

**Random , linespace and identity**

In [4]:
np.random.random((3,2))

array([[0.45979709, 0.38921172],
       [0.19609882, 0.00773662],
       [0.72222341, 0.88661371]])

linear space = it will provide you the nos. between a range and nos. are placed with a equal length in the range

In [174]:
out = np.linspace(-10,20,7)
print(out)

[-10.  -5.   0.   5.  10.  15.  20.]


In [175]:
import numpy as np

# Corrected function call
result = np.linspace(-10, 10, 10)
print(result)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [176]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

**ndim = No. of dimensions**

In [177]:
print(a.ndim)

2


In [178]:
b.ndim

2

In [179]:
c.ndim

3

**ndmin = set any dimension to an array**

In [180]:
x= np.array([1,2,3],ndmin=10)
x

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [181]:
y= np.array([1,2,3],ndmin=3)
y

array([[[1, 2, 3]]])

**dtype & astype**

In [182]:
n = np.array([1,2,3])
n.dtype

dtype('int32')

In [183]:
n =np.array([1.2,2.3,4.1])
n.dtype

dtype('float64')

*set dtype*

In [184]:
n = np.array([1,3,2],dtype ="float")
n.dtype
n

array([1., 3., 2.])

In [185]:
n = np.array([1,3,2],dtype ="complex")
n.dtype
n

array([1.+0.j, 3.+0.j, 2.+0.j])

In [186]:
a = np.array([1,2,3])
a.astype(float)

array([1., 2., 3.])

In [187]:
a = np.array([1.,2.,3.])
a.astype(int)

array([1, 2, 3])

In [188]:
a = np.array([1,2,3])
a.astype(complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [189]:
a = np.array([0,1,0,1,1,0,0,0,1])
a.astype(bool)

array([False,  True, False,  True,  True, False, False, False,  True])

In [190]:
n = np.array([1.2,3.2,2.9],dtype ="int")
n.dtype
n

array([1, 3, 2])

**shape , reshape and aranage**

In [191]:
n = np.array([1,3,2],dtype ="float")
n.shape

(3,)

In [192]:
m = np.array([[1,2,3],[3,5,6]])
m.shape

(2, 3)

In [193]:
m = np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [194]:
m.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [195]:
m.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [196]:
r = np.arange(24)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [197]:
r.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [198]:
r.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [199]:
r.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [200]:
r.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

**Size and Itemsize**

In [201]:
import numpy as np

In [202]:
n = np.array([1,2,3,4,5,6,7,8,9,10])
n.size

10

In [203]:
m = np.array([[1,2,3],[3,4,4]])
m.size

6

In [204]:
n = np.array([1,2,4,3])
print(n.dtype)
print(n.itemsize)

int32
4


In [205]:
# What if , i can change int32 to int64  --> itemsize = 8
n = np.array([1,2,4,3] , dtype = "int64")
print(n.dtype)
print(n.itemsize)

int64
8


In [206]:
n= np.array([1.2,2.1,4.7,4.])
print(n.dtype)
print(n.itemsize)

float64
8


## Array Operations

**Scalar Operation**

In [207]:
# Arithmetic Operations

a = np.array([1,2,3,4,6,8])
print(a+2)
print(a*2)
print(a/3)
print(a%2)

[ 3  4  5  6  8 10]
[ 2  4  6  8 12 16]
[0.33333333 0.66666667 1.         1.33333333 2.         2.66666667]
[1 0 1 0 0 0]


In [208]:
# Relations Operator

a = np.linspace(5,50,10)
a.astype(int)

print(a>20)
print(a<40)
print(a==10)
print(a!=10)


[False False False False  True  True  True  True  True  True]
[ True  True  True  True  True  True  True False False False]
[False  True False False False False False False False False]
[ True False  True  True  True  True  True  True  True  True]


**Vector Operations**

In [209]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(1,17).reshape(4,4)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [210]:
print(a+b)
print(a*b)
print(a>=b)
print(a>b)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


## Array Funtions

**min/max/sum/product**

In [211]:
np.min(a)
# 0 --> column
# 1--> row

1

In [212]:
# row wise min
np.min(a, axis=1)

array([ 1,  5,  9, 13])

In [213]:
# column wise min
np.min(a, axis=0) 

array([1, 2, 3, 4])

In [214]:
print(np.max(a))

# row wise max
print(np.max(a,axis=1))

# column wise max
print(np.max(a,axis=0))

16
[ 4  8 12 16]
[13 14 15 16]


In [215]:
# you can find product and sum row and column wise
print(np.sum(a))
print(np.product(a))

136
2004189184


**mean , median , std , variance**

In [216]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [217]:
np.mean(a,axis=0)

array([3., 4., 5.])

In [218]:
print(np.median(a,axis=1))
print(np.std(a))
print(np.var(a,axis= 1))

[1. 4. 7.]
2.581988897471611
[0.66666667 0.66666667 0.66666667]


**dot product of matrix**


In [219]:
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)
np.dot(a,b)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

**round/ floor/ cell**

In [220]:
a = np.random.random((3,3))
a

array([[0.18129115, 0.46067973, 0.66165949],
       [0.0568325 , 0.78597636, 0.41237972],
       [0.38043998, 0.32219887, 0.71009753]])

In [221]:
# round = round-off
np.round(a)

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [222]:
# floor = lower interger round off
np.floor(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [223]:
# ceil = upper integer round off
np.ceil(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Iterating**

In [224]:
a = np.arange(10)
for i in a:
    print(i)



0
1
2
3
4
5
6
7
8
9


In [225]:
b = np.arange(12).reshape(3,4)
for i in b:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [226]:
c = np.arange(8).reshape(2,2,2)
for i in c:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


*nditer*

In [227]:
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5
6
7


**reshape , transpose and ravel**

In [228]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [229]:
np.transpose(a) 

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [230]:
a.T # another way to transpose 

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [231]:
# ravel = it converts n dimension array into 1-D array
np.ravel(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**Stacking**

In [232]:
# vertically stack = adding array vertically
# horizontal stack = adding array horizontally

In [233]:
a = np.arange(12).reshape(3,4)
b = np.arange(20,32).reshape(3,4)
c= np.arange(10,22).reshape(3,4)


In [234]:
print(np.vstack((a,b)))
print()
print(np.vstack((a,b,c)))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [235]:
print(np.hstack((b,a)))
print()
print(np.hstack((a,b,c)))

[[20 21 22 23  0  1  2  3]
 [24 25 26 27  4  5  6  7]
 [28 29 30 31  8  9 10 11]]

[[ 0  1  2  3 20 21 22 23 10 11 12 13]
 [ 4  5  6  7 24 25 26 27 14 15 16 17]
 [ 8  9 10 11 28 29 30 31 18 19 20 21]]


**Splitting**

In [236]:
np.hsplit(a,2)  # np.hsplit(array,no of division)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [237]:
np.vsplit(b,3)  # np.split(array, no of division)

[array([[20, 21, 22, 23]]),
 array([[24, 25, 26, 27]]),
 array([[28, 29, 30, 31]])]

In [238]:
x = np.hstack((a,b,c))

# lets split this big horizonatal array (3X12)
np.hsplit(x,3)
np.hsplit(x,4)
np.hsplit(x,6)
np.hsplit(x,12)
# we can go any further , because array is no more divisible


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[20],
        [24],
        [28]]),
 array([[21],
        [25],
        [29]]),
 array([[22],
        [26],
        [30]]),
 array([[23],
        [27],
        [31]]),
 array([[10],
        [14],
        [18]]),
 array([[11],
        [15],
        [19]]),
 array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]])]

In [239]:
# Similaray we can do same for vsplit
y = np.vstack((a,b,c))