**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [8]:
#Code here
a = np.nan*(np.empty(10))
a[4]= 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [13]:
#Code here

input


a= 3
b =4

r = np.random.randint(1,100,(a,b))

av = np.average(r)
av

45.916666666666664

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [9]:
#Code here

a = np.ones((4,4),dtype ="int")
a[1:-1,1:-1] = 0
a

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [13]:
#Code here
a = np.random.random(10)
a

# Or

b = np.linspace(0,1,10)[1:-1]
b

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:

#NOO

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [18]:
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [24]:
x1 = np.random.randint(1,100,(10,2))
point = np.array([2,3])

x1 

array([[28, 89],
       [71, 68],
       [26, 93],
       [79,  9],
       [47,  4],
       [43, 93],
       [15, 55],
       [84, 79],
       [61, 54],
       [40, 33]])

In [31]:
np.sqrt(np.sum(x1-point,axis=1))

array([10.58300524, 11.5758369 , 10.67707825,  9.11043358,  6.78232998,
       11.44552314,  8.06225775, 12.56980509, 10.48808848,  8.24621125])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [36]:
a = np.random.randint(1,1000, (6,7,8))

np.unravel_index(100,(6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [42]:
a = input().strip().split()
x = np.array(a,dtype='float')
x[::-1]

array([234.,   2.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [45]:
a = input().strip().split()

x = np.array(a)
x.size

0

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [62]:
def vertical_stack(*args):
    for i in args:
        if(type(i)!= np.ndarray):
            raise TypeError("Requires Python array")
    return np.vstack(args)

a = np.arange(10).reshape(2,5)
b = np.random.randint(10,100,(2,5))
c = np.random.randint(10,20,(2,5))
d = np.random.randint(1,10,(2,5))

print(vertical_stack(a,b,c,d))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [61 27 82 79 23]
 [82 93 77 70 93]
 [19 15 19 16 10]
 [18 11 14 17 18]
 [ 4  6  3  3  1]
 [ 1  4  1  8  9]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract every element with the mean of each row from a matrix.

In [76]:
s = np.random.randint(1,50,(5,3))
print(s)

x = s.mean(axis=1,keepdims=True)  # Two array of 5,1 ( 5 row index)
print(x)

s-x   # result 


[[25  7 29]
 [35 29 25]
 [14  8 37]
 [11 16 36]
 [ 6 14 43]]
[[20.33333333]
 [29.66666667]
 [19.66666667]
 [21.        ]
 [21.        ]]


array([[  4.66666667, -13.33333333,   8.66666667],
       [  5.33333333,  -0.66666667,  -4.66666667],
       [ -5.66666667, -11.66666667,  17.33333333],
       [-10.        ,  -5.        ,  15.        ],
       [-15.        ,  -7.        ,  22.        ]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [89]:
x = np.arange(9).reshape(3,3)

x[:, [0,2,1]]  # swapping column 1 with column 2

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [90]:
a = np.arange(50)
a[a%2!=0] = -1
a


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1,
       34, -1, 36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
    ``

In [91]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [92]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

arr1[:, ::2]  # alternate columns

array([[1703, 2539, 8106, 9094, 5454],
       [6620, 6675, 7979,  382, 1570],
       [2268, 5534, 4311, 7468, 4009],
       [ 365, 3836, 2767, 3670, 4358],
       [9111, 7230, 9782, 3873, 8113],
       [4304, 4113, 8574, 5148, 6360],
       [5721, 1975, 2818, 8162, 9170],
       [5092, 1237, 7545, 4103, 7255]])

In [110]:
# Normalization
N =  arr1 - np.min(arr1)
D = np.max(arr1) - np.min(arr1)

Normalization = N/D
Normalization

array([[0.14208347, 0.23085908, 0.822024  , 0.92694064, 0.54040565],
       [0.66422428, 0.67006478, 0.80853775, 0.00180525, 0.12796007],
       [0.20208134, 0.54890092, 0.41902941, 0.75427418, 0.38695975],
       [0.        , 0.36858872, 0.25507062, 0.35096103, 0.42402039],
       [0.92874589, 0.72900074, 1.        , 0.37251779, 0.82276734],
       [0.41828608, 0.39800361, 0.87172135, 0.50791122, 0.63661463],
       [0.56875863, 0.1709674 , 0.26048635, 0.82797069, 0.93501115],
       [0.50196453, 0.09259849, 0.76245089, 0.3969417 , 0.73165552]])

###`Q-19:` Write a function which will accept 2 arguments.

First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [118]:
def function(arr,n):
    if(n>len(arr)):
        raise IndexError("n is way out of limit")
    arr.sort() #acsending order 
    return arr[-n]

function(np.array([12,4,2,123,10,235,883]),2)



235

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [134]:
#Hero -- tile() and repeat() function

a = np.array([1,2,3])

a1 = np.repeat(a,3)
print(a1)

a2 = np.tile(a,3)
print(a2 )

result = np.hstack((a1,a2))
result

# output = np.hstack([np.repeat(a,3) , np.tile(a,3)]) // Without Variable
# print(output)



[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])